#!/usr/bin/bash

#xhost local:root

xhost +

docker run --rm \
           -i \
	   --device /dev/dri \
	   --device /dev/snd \
	   --device /dev/usb \
	   --device /dev/bus/usb \
           --net=host \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
	   -v /home/fluna/GNURadio_projects:/home/builder/projects \
	   -v /home/fluna/dediqs:/home/builder/dediqs \
           -e DISPLAY=$DISPLAY\
           -t docksphor \
           bash
